### PR TITLE
Ew initial db

### PR DESCRIPTION
**Pull request by ewilliamswtn**
## Changelog
- Program.cs now calls DatabaseSeed.createTables() method
-  This method uses a ```try``` to seed data to the database; and a ```catch``` to handle the sqlite error, if any data is already present.

## To Test
- git fetch
- git checkout -b ew-initialDb
##### Check that database seeds
- check your new database, make sure no data exists
- run program
- check database again, verify data now exists
##### Check that program functions correctly if data exists
- after the steps above, run program again
- if no errors are present, program is working as intended

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by estorms** [comment]
womm

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
finally fucking womm.

**Pull request merged**
