### PR TITLE
added additional tests for incident and employee, added customer, inc…

### PR DESCRIPTION
**Pull request by estorms**
…ident, incidenttype, order classes

Details:

As a team, we

1. created additional tests on employee, including test on method to get employee by id that that successfully throws errors

2. began creating tests on incident class

3. built out order, customer, incident, incident type classes

To test:

1. git fetch
2. git checkout employee-tests
3. open the project
4. run all 8 tests and insure that every one passes except CanGetIncidentsByEmployeeAssigned, which should throw a MethodNotImplemented error
5. check that specified classes exist in project

### CODE REVIEW

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
WOMM on my windows machine!

**Comment by ewilliamswtn** [comment]
👍

**Comment by flawavi** [comment]
womm

**Pull request merged**
