### PR TITLE
more tests on incident

### PR DESCRIPTION
**Pull request by estorms**
Details:

As a team, added additional tests to IncidentTest.cs, including test method to search for incident by its id.

To test:

1. Git fetch
2. Git checkout es-more-tests
3. Insure test called CalledGetIncidentById is included and throws NotImplementedException when tests are run

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
womm!

**Comment by ewilliamswtn** [comment]
womm

**Pull request merged**
