### PR TITLE
Fw tests

### PR DESCRIPTION
**Pull request by flawavi**
git checkout fw-tests

1. Make sure they [Key] decoration has been removed from classes.
2. Make sure there is a new save method on the Employee class.
3. Make sure that the EmployeeTest file includes a test for getting a single employee.

### CODE REVIEW

**Comment by estorms** [comment]
lgtm

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍 L👍 G👍 T👍 M👍

**Pull request merged**
